baseURL: 'https://teraskula.com/'
languageCode: 'en-us'
title: 'teraskula.com'
theme: 'PaperMod'
publishDir: 'docs'
params:
  comments: true
  homeInfoParams:
      Title: Kulonuwun (Hi)
      Content: Not Much, Software Technology, Universe
  socialIcons: # optional
      - name: "github"
        url: "https://github.com/prima101112"
      - name: "strava"
        url: "https://strava.com/athletes/87122737"
taxonomies:
  categories: 'categories'
  tags: 'tags'
menu:
    main:
        - name: About
          url: /posts/about-teraskula/
          weight: 10
        - identifier: categories
          name: categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20

